<a href="https://colab.research.google.com/github/keinam53/NumPy_Matplotlib_ScyPy/blob/main/1_NumPy/1_NumPy_wprowadzenie.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###NumPy - wprowadzenie
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)

### <a name='a1'></a> Podstawy

In [1]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
dir(np)

In [ ]:
help(np.array)

1D Array

In [5]:
x = np.array([1, 3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
print(type(x))

<class 'numpy.ndarray'>


In [8]:
#Wymiar tablicy
x.ndim

1

In [9]:
#Kształt tablicy
x.shape

(2,)

In [10]:
#Rozmiar tabl
x.size

2

In [11]:
#Typ
x.dtype

dtype('int64')

In [13]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [14]:
x.dtype

dtype('float64')

2D Array

In [15]:
x = np.array([[1, 3], [-2, 5]])
print(x)

[[ 1  3]
 [-2  5]]


In [16]:
x.ndim

2

In [17]:
x.shape

(2, 2)

In [22]:
x = np.array([[1, 4, 6], [3, 4, 8]])
print(x)

[[1 4 6]
 [3 4 8]]


In [23]:
x.shape

(2, 3)

3D Array

In [ ]:
x = np.array([[[]]])

In [35]:
x = np.array([[[1, 2, 3], [4, 5, 6]],
              [[4, 5, 6, ], [5, 1, 3]],
              [[5, 8, 9,], [1, 8, 5]]])
              
print(x)

[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [5 1 3]]

 [[5 8 9]
  [1 8 5]]]


In [36]:
x.ndim

3

In [37]:
x.shape

(3, 2, 3)

### <a name='a2'></a> Typy danych

In [38]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [39]:
A = np.array([0.4, 1, 4.3])
A.dtype

dtype('float64')

In [40]:
A = np.array([1, 3, 7], dtype='float')
A.dtype

dtype('float64')

In [42]:
#complex - typ liczb złożonych
A = np.array([1, 3, 7], dtype='complex')
print(A.dtype)
print(A)

complex128
[1.+0.j 3.+0.j 7.+0.j]


In [44]:
A = np.array([1.1, 3.1, 7.9], dtype='int')
print(A.dtype)
print(A)

int64
[1 3 7]


In [45]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [46]:
A = np.array([24, 128, 230], dtype='uint8')
A.dtype

dtype('uint8')

### <a name='a3'></a> Tworzenie tablic

In [47]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [51]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [52]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [54]:
np.arange(5, 100, 10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [55]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [56]:
np.arange(0, 1, 0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [58]:
np.linspace(0, 1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [60]:
A = np.arange(0, 15, 1)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [61]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
#Jeśli podamy wartość -1 to python obliczy optymalną wartość
A.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
A.reshape(-1, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [65]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [67]:
#Długości tablic muszą się zgadzać!
A + B

array([6, 0, 7, 4])

In [68]:
A - B

array([0, 2, 1, 0])

In [69]:
A * B

array([ 9, -1, 12,  4])

In [70]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [74]:
np.add(A, B)

array([6, 0, 7, 4])

In [75]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [76]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [77]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [71]:
#Dodanie liczby do każdego elementu
A + 3

array([6, 4, 7, 5])

In [72]:
A * 2

array([6, 2, 8, 4])

In [73]:
A + 3 * B

array([12, -2, 13,  8])

In [78]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [83]:
#mnożenie macierzowe
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [80]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [81]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [82]:
X @ Y

array([[  3,   6],
       [-12,   0]])

### <a name='a5'></a>  Generowanie liczb pseudolosowych

In [84]:
np.random.seed(0)

In [85]:
#Losowanie z rozkładu normalnego
np.random.randn()

1.764052345967664

In [86]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [87]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [88]:
#Losowanie z przedziału (0, 1)
np.random.rand()

0.1965823616800535

In [89]:
np.random.rand(10, 2)

array([[0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947],
       [0.4686512 , 0.97676109],
       [0.60484552, 0.73926358],
       [0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145]])

In [94]:
#Losowanie liczby int od 0 do wartości w nawiasie
np.random.randint(10)

4

In [95]:
np.random.randint(low=10, high=101, size=10)

array([20, 96, 53, 21, 12, 61, 90, 42, 64, 10])

In [96]:
#Losowanie dowolnego elementu z listy
np.random.choice([4, 1, 2, 3, 6])

3

In [97]:
np.random.choice(['python', 'java', 'sql'])

'sql'

In [98]:
data = np.arange(10)
print(data)

[0 1 2 3 4 5 6 7 8 9]


In [99]:
#Tasowanie wartości w tablicy
np.random.shuffle(data)
print(data)

[7 9 2 1 6 5 0 4 8 3]


### <a name='a6'></a> Podstawowe funkcje

In [100]:
#Exponent
np.exp(1)

2.718281828459045

In [101]:
#pierwiatsek
np.sqrt(9)

3.0

In [102]:
#Testowanie danych
np.all([1, 4, 2])

True

In [103]:
np.any([1, 2, 1])

True

In [104]:
A = np.random.randn(5)
A

array([ 0.3869025 , -1.05075796,  1.01207905,  1.54371643, -0.40211489])

In [105]:
#Wartość maksymalna (index)
np.argmax(A)

3

In [106]:
#Wartość minimala (index)
np.argmin(A)

1

In [107]:
#Sortowanie wartości (po indexie)
np.argsort(A)

array([1, 4, 0, 2, 3])

In [108]:
np.max(A)

1.5437164304718984

In [109]:
np.min(A)

-1.0507579569860566

In [110]:
np.mean(A)

0.2979650270946784

In [111]:
np.median(A)

0.386902497859262

In [112]:
np.std(A)

0.9358344781181064

###  <a name='a7'></a> Indeksowanie, Wycinanie


In [114]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [115]:
A[2]

2

In [116]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [117]:
A[:2]

array([0, 1])

In [118]:
A[[0, 2]]

array([0, 2])

In [119]:
A[-1]

19

In [120]:
A[10:15]

array([10, 11, 12, 13, 14])

In [122]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [123]:
#Wycinanie wiersza
A[1]

array([5, 6, 7, 8, 9])

In [124]:
#Wycinanie kolumny
A[:, 1]

array([ 1,  6, 11, 16])

In [125]:
#Wycinanie konkretnego elementu (przecięcie kolumny i wiersza)
A[1, 2]

7

In [126]:
#Wycięcie przedziału
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [128]:
#Przypisanie nowych wartości
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach


In [129]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [130]:
#Iteracja po wierszach
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [131]:
for row in A:
    print(row[0])

0
5
10
15


In [132]:
#Iteracja po elementach
for item in A.flat:
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [133]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [134]:
A.shape

(4, 5)

In [135]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [136]:
#Wypłaszczenie tablicy
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [137]:
A.transpose()

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

In [140]:
A = np.arange(-10, 10, 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [141]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [142]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [143]:
 #Dwa lub więcej warunków
 np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [145]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [146]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [147]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])