<a href="https://colab.research.google.com/github/keinam53/NumPy_Matplotlib_ScyPy/blob/main/1_NumPy/3_Funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Funkcje statystyczne

In [1]:
import numpy as np

price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [2]:
price.shape

(3, 5)

##sum()

In [3]:
price.sum()

4650.1

In [4]:
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [5]:
price.sum(axis=1)

array([1049.7, 2049.4, 1551. ])

##min()

In [6]:
np.min(price)

11.7

In [7]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

##max()

In [8]:
np.max(price)

2000.0

In [9]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

##median()

In [10]:
np.median(price)

12.6

In [11]:
np.median(price, axis=0)

array([  12.4,   13. ,   11.9,   12.6, 1500. ])

##mean()

In [12]:
np.mean(price)

310.0066666666667

In [13]:
np.median(price, axis=0)

array([  12.4,   13. ,   11.9,   12.6, 1500. ])

##std()

In [14]:
np.std(price)

622.3781502877133

In [16]:
np.set_printoptions(precision=4, suppress=True)

np.std(price, axis=0)

array([  0.1247,   0.2494,   0.2055,   0.411 , 408.2483])

##var()

In [17]:
np.std(price)

622.3781502877133

In [18]:
np.var(price, axis=0)

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])